services:
  db:
    container_name: ${DB_CONTAINER_NAME}
    image: "mongo:latest"
    environment: 
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD}
    ports:
      - "${DB_ACCESS_PORT}:27017"
volumes:
  todo-list-api-mongo: