services:
  db:
    container_name: ${DB_CONTAINER_NAME}
    image: "mongo:latest"
    environment: 
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD}
    ports:
      - "${DB_ACCESS_PORT}:27017"
  
  cache:
    container_name: ${CACHE_CONTAINER_NAME}
    image: redis:7.4.2-alpine3.21
    restart: unless-stopped
    ports:
      - "${CACHE_ACCESS_PORT}:6379"
    command: redis-server --save 60 1 --loglevel warning

volumes:
  todo-list-api-mongo: